### ISSUE TITLE
IPython 8.2.0 freezes very often

### ISSUE THREAD

**Issue by Barzi2001** [hoangKnLai/vscode-ipython#10]
`IPython 8.2.0 `freezes very often especially when I try to paste something in it.
This won't happen with the `VSCode` built-in `Python Interactive window`. 
Running on `Windows 10`.

**Comment by hoangKnLai** [comment]
Hi.  It's hard to tell what might be the problem since this IPython extension only send text to the IPython console.  You might be able to examine the cause further by:  
- Test IPython console run without VSCode: on your computer command line terminal (e.g., git bash) starts IPython `$ ipython`
- Run your code there and see if freeze problem persists

If it persists without VSCode, then it is your IPython environment setup (e.g., running IPython exe over network).

**Comment by Barzi2001** [comment]
Yes, I love your extension because it just does what it is supposed to do. 
However: 
- IPython 8.2.0 freezes on both VSCode and on Vim + vim-repl. It won't freeze on a ipython terminal or on Spyder.
- IPython 7.1.9 won't freeze anywhere.

**Comment by hoangKnLai** [comment]
Thanks!  Glad you're enjoying the extension 😄.  

> IPython 7.1.9 won't freeze anywhere.

This sounds like a IPython install problem.  You might want to do a clean install for the IPython package.  Also, IPython got a lot of auto options like autoformatting, auto-indent that you probably want to turn off; see https://ipython.readthedocs.io/en/stable/config/options/terminal.html.

**Comment by Barzi2001** [comment]
Yes, your extension just do what is needed, without too many bells & whistles. It's just perfect and I love it! :) 

Back to the problem: I have completely reinstalled `Anaconda `and now everything seems to work fine. 

**Small request**: would that be possible to update the extension such that `F9 ` ->  `sends the current line`, like it happens in `Spyder `and perhaps in `Matlab`? :) 
Or, can you explain how to add such a shortcut on my `VSCode` so perhaps I can do it by myself?
Sorry but I am very new in `VSCode.` :)

**Comment by Barzi2001** [comment]
Ah ok, but still a `SendCurrentLine `option could be still useful. Then one could key bind it wherever he/she wants (not necessarily on `F9`) :)
