### ISSUE TITLE
Send multi-line selection as a block

### ISSUE THREAD

**Issue by cameronbracken** [hoangKnLai/vscode-ipython#17]
When multiple lines are selected and It would be great to have all the lines sent as a block instead of one by one. When lines are copy-pasted this is how they are input.

**Comment by hoangKnLai** [comment]
Is this not the case?  Here is an example of multi-cursors each with single or multi-lines or words selected and run.  Note that all lines across all cursor are indent corrected before being sent to IPython. 
![image](https://user-images.githubusercontent.com/64025449/189529139-a84b7930-f0a8-4d87-9e9c-937492469b9d.png)

Also, a single multi-line selection with corrected indentation:  
![image](https://user-images.githubusercontent.com/64025449/189529224-3f49625a-dcae-4dbd-afbc-55fae6e6814d.png)

**Comment by cameronbracken** [comment]
Your screenshots look like how I would expect it to work, but when I run "IPython: Run Code Selection(s) or Line at each Cursor", it looks like this for me: 
![Screen Shot 2022-09-12 at 9 39 33 AM](https://user-images.githubusercontent.com/32280/189710107-490d8099-b2b6-4aa2-9bc9-2d506849aaa0.png)
![Screen Shot 2022-09-12 at 9 39 57 AM](https://user-images.githubusercontent.com/32280/189710135-6683c908-b1cb-459a-8db7-1e2672dd5ff0.png)



![Screen Shot 2022-09-12 at 9 40 40 AM](https://user-images.githubusercontent.com/32280/189710162-4a818256-6436-4355-b630-a153872a0b82.png)
![Screen Shot 2022-09-12 at 9 40 58 AM](https://user-images.githubusercontent.com/32280/189710201-97dee6ba-7678-4d24-9c46-7bb099e4dff7.png)

**Comment by hoangKnLai** [comment]
That is interesting.  The older version does execute line-by-line but should be fixed in v2022.9.x.  Can you confirm the version of the extension you're using?

**Comment by ma-sadeghi** [comment]
I'm using the latest version, and it's line-by-line

**Comment by cameronbracken** [comment]
I'm on `v2022.9.2`

**Comment by hoangKnLai** [comment]
K. Let's look at something else since I'm unable to replicate the problem.  Can you guys provide a bit on the computing system/environment you're using? Like, Window vs. Linux.  

Also, I've found that the Jupyter extension tends to conflict with this extension.  It might help with diagnoses by disabling the Jupyter extension to check.

**Comment by hoangKnLai** [comment]
I was able to replicate the problem when testing on a Linux Debian environment.  Hopefully it is not the case that IPython behaves differently between the two systems.  Build and test the extension on Linux requires `npm, yo, vsce` packages and they are so far a serious pain to build (still can't build them all yet). 

"There should be one-- and preferably only one --obvious way to do it." Zen of Python.

**Comment by hoangKnLai** [comment]
It appears to be a case of IPython behaving differently between Linux and Window.  Anyhow, I might the hotfix for this.  Will have to test it out more releasing this weekend.

**Comment by cameronbracken** [comment]
Thanks for looking into this! I am on MacOS so it is probably behaving similarly to Linux in this case.

**Comment by hoangKnLai** [comment]
Ok.  Tested the `v2022.09.3` fix and it works on both Linux and Window.  If it works for you, please confirm and close this issue.  

Also, in case you're interested, the fix includes:
- Sending the text using clipboard paste instead of `terminal.sendText` command
- The cursor might blink irregularly because the clipboard copy/paste by moving the cursor to the terminal and then paste there.  I chose to jump the cursor back to the editor since most of the time it is more useful to stay in the editor.  

There might be an unintended effect with the copy/paste:
- When using the clipboard to send command to the terminal, the clipboard buffer is copied to vscode memory, replaced by the command text and pasted onto the terminal, and finally the previous clipboard is copied back onto the buffer.
- The clipboard buffer might be large -> vscode might slowdown significantly or other memory issue

A better solution likely includes: 
- Add IPython REPL to VSCode instead of being an overload of the bash terminal   
- Somehow connect the IPython API (python) with VSCode typescript  
- IPython team improves their stdin text management and API in general

**Comment by cameronbracken** [comment]
It works great on MacOS too! Thanks so much for the fix. 

And thanks for the heads up about the potential slowness when the clipboard buffer is large.

**Comment by cameronbracken** [comment]
Looks like we are back to the old behavior of sending one line at a time, on MacOS at least. I'm using ipython v2023.2.3 and vscode 1.76.0.

**Comment by hoangKnLai** [comment]
Sorry about that.  Forgot to test on Linux/Unix system.  Will release a fix soon.  

Anyhow, have you try out the `file` option to send command? It should be quite a bit faster than the `clipboard` when it comes to large block of code.
