### ISSUE TITLE
Make ipython executable configurable

### ISSUE THREAD

**Issue by W4RH4WK** [hoangKnLai/vscode-ipython#20]
Hey there. Please make the ipython executable used by the extension configurable.

Furthermore, it should default to `ipython.exe` on Windows.

**Comment by hoangKnLai** [comment]
Hi! Just to clarify, are you having trouble setting `PATH` such that `ipython.exe` is recognized by the `terminal` such as `bash` for example?  If so, you might want to take a look at:
- [VSCode docs on terminal](https://code.visualstudio.com/docs/terminal/profiles) for how terminal startup option you might be able to use to setup `PATH` variable
- Setting up terminal environment such as that of [`bash` terminal](https://opensource.com/article/17/6/set-path-linux) 

Basically, this IPython extension simply "borrows" the current Python environment on your active terminal to startup the `ipython.exe`.  The `ipython.exe` then overload the terminal.  So you can always control which `ipython.exe` to use by setting the terminal `PATH` variable to point to the exact `ipython.exe` to use.  At the moment, I prefer the extension does not supersede the terminal `PATH` variable since this is already well handle by vscode terminal options. 

Generally, `python` software is better written using `virtualenv` so you might want to take a look setting up virtualenv.   `MS Python` extension already has quite a good support for the virtualenv.  Note that the virtualenv can be setup to contains your specific `ipython.exe` and all other packages you might need for your project.

**Comment by W4RH4WK** [comment]
Alright, thanks for the clarification. The Python setup(s) on my machine are a bit over-complicated since I do have to use different versions of Python (some with custom patches) to get certain software (mainly AI image upscaling stuff) to work properly. I've also run into issues with `virtualenv` because of which I typically don't use it for small projects that don't have any dependencies beyond the standard library.

I'll just set the path appropriately for VSCode.
