### ISSUE TITLE
Feature request: run file in the file directory.

### ISSUE THREAD

**Issue by chinabiue** [hoangKnLai/vscode-ipython#23]
Like in VScode default python interpreter. when I click run button , the terminal will auto 'cd' to the file directory, and then run the file, which we can have a setting in "Python.Terminal.Execute in File Dir".
I can not figure out a way to do this when using vscode-ipython extension. I think there is a way to achieve this using "Ipython.Startup Commands", but I failed. 
is any one can achieve this or we need a new feature to run ipython in File Dir?

**Comment by hoangKnLai** [comment]
Hi, while I'm thinking about adding this as a new feature, here are some options you might want to try.  
- On the `ipython` terminal, you can manually `cd directory_of_file` 
- [PYTHONPATH](https://docs.python.org/3/library/sys_path_init.html) setup with [VSCode ](https://code.visualstudio.com/docs/python/environments#_use-of-the-pythonpath-variable) to manage the working directory without having to use `cd`. 

Side note, I'm familiar with the `run in file dir` feature but found it in the past to be a poor feature.  Because changing directory of the terminal to run a file can sometime be a problem with the environment variables.  Just out of curiosity, can you describe what the use case here for this feature? Thanks!

**Comment by chinabiue** [comment]
When writting a py file with reference to other file contents(txt/csv/excel...) which put together with py file.
this situation can not success when cwd is your home directory. I have to switch to the file dir first then run it. :)
Any way, thanks for your response. your suggestion is kind of solution for me. Thanks.
