### ISSUE TITLE
request: dedicated colour for the Terminal tab running Ipython

### ISSUE THREAD

**Issue by cmorgan** [hoangKnLai/vscode-ipython#55]
Would this be easy to do? Is there a way to do such a thing already?
Cheers!

**Comment by hoangKnLai** [comment]
Thank you for the suggestion.  Will look into it.

**Comment by hoangKnLai** [comment]
Hi.  I've look into this and here are the finding so far: 
- Currently this extension is piggyback off of the `MS Python` extension to create the terminal  
   - This issue is likely better on the `MS Python` than here.
- There appear to be very limited option in `VSCode` API for terminal UI customization
