### ISSUE TITLE
Run multi-line selection or section without %run

### ISSUE THREAD

**Issue by dmn-seasony** [hoangKnLai/vscode-ipython#58]
If I execute the `ipython.runSelections` command with a single line selected, the line is directly copied to the terminal and executed. However if I select multiple lines or use the `ipython.runSection` command, the code instead gets saved to a file (`~/.vscode/ipython/code.py`) and executed with the `%run -i` magic.

However I would like to be able to directly see the lines that are executed in the terminal, and to see the return value of the last line (without explicitly using `print`), same as if I had typed the code directly into the terminal. It works fine to just copy the code and paste it into the terminal but that is cumbersome to do manually. Would it be possible to do that with this plugin?

**Comment by hoangKnLai** [comment]
Hi.  I'll take a look but here some past solution that didn't work out:  
- Use of the [%load](https://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-load) command which prints all the lines on screen
   - This one is awkward since IPython terminal execute the loaded code differently dependent on the tabbing situation of the last line
   - Some people reported this being slow and clutter the terminal. This leads to the `%run -i .../code.py` option.
- Use the system copy / paste buffer of multi line to screen
   -  Can be intrusive and can cause additional operating runtime integrity problem. I.e., messes up the copy / paste buffer and sometime paste very random things to terminal on slower computer!

As for printing the last line.  IPython terminal by default doesn't print unless the code explicitly calls `print()` or a variable by itself being called in the terminal.  Changing IPython terminal behavior is out of scope of this extension.  So a compromise is that you can highlight the variable (double click or other selection method) and `Run Selection (F9)` handles the sending of text to the terminal.  Also, consider the following:  

```python
for i in range(4): 
    ii = i + 1

if False:
   ii + 3
```
How should `ii` be printed? Every line or just last line? It is ambiguous and there will be use-case where neither one works.  In the `if` case, it should never be printed but to know when to print would requires knowing the code / sequence of event vs. current workspace variable;  i.e., a real big mess!  So, for now, the likely best apparent answer is that you as a developer should explicitly use print when appropriate and use highlight + F9 to print specific workspace variable you like to see. 

Onto the seeing the exact code being executed question.  One way is to open the `code.py` in an editor like below.  VSCode update `code.py` and you can see the changes live.  

![image](https://github.com/hoangKnLai/vscode-ipython/assets/64025449/ca168147-7a9a-44dc-96d3-1e84410546ce)

Hope this helps and thank you for posting! Any suggestion or comment are always welcome and appreciated.
